name: Deploy (prod)

on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: |
        yarn install
        yarn install --cwd functions

    - name: Copy .env
      run: yarn run env:prod --cwd functions

    - name: build
      run: yarn build:prod

    - name: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: yarn firebase -P prod deploy --token $FIREBASE_TOKEN

