name: Deploy (only master)

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: |
        yarn install
        npm ci --prefix functions

    - name: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: yarn firebase -P prod deploy --token $FIREBASE_TOKEN

