name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: contrib.rocks

  run-deploy:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/deploy-production.yml
    with:
      ref: ${{ github.sha }}
    secrets: inherit
